---
paperlessng_version: 0.9.9
paperlessng_directory: /opt/paperless-ng
paperlessng_consumption_dir: "{{ paperlessng_directory }}/consumption"
paperlessng_data_dir: "{{ paperlessng_directory }}/data"
paperlessng_media_root: "{{ paperlessng_directory }}/media"
paperlessng_static_dir: "{{ paperlessng_directory }}/static"
paperlessng_filename_format:
paperlessng_virtualenv: "{{ paperlessng_directory }}/.venv"

paperlessng_ocr_languages:
  - eng
paperlessng_time_zone: Europe/Berlin
paperlessng_ocrmypdf_args: --optimize 1
# TODO Does optimze==1 really work with jbig2enc?
# https://ocrmypdf.readthedocs.io/en/latest/jbig2.html#lossy-mode-jbig2
# Documentation states -O1 only applies lossless transformations
# https://ocrmypdf.readthedocs.io/en/latest/optimizer.html#lossless-optimizations
paperlessng_use_jbig2enc: true

paperlessng_superuser_name: paperlessng
paperlessng_superuser_email: paperlessng@example.com
paperlessng_superuser_password: paperlessng

paperlessng_system_user: paperlessng
paperlessng_system_group: paperlessng

paperlessng_listen_address: 127.0.0.1
paperlessng_listen_port: 8000

paperlessng_redis_host: localhost
paperlessng_redis_port: 6379

paperlessng_db_type: sqlite # or postgresql
# Below entries only apply for paperlessng_db_type=='postgresql'
paperlessng_db_host: localhost
paperlessng_db_port: 5432
paperlessng_db_name: paperlessng
paperlessng_db_user: paperlessng
paperlessng_db_pass: paperlessng
