language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install --upgrade pipenv
  - pipenv install --dev

script:
  - cd src/
  - pipenv run pytest --cov
  - pipenv run pycodestyle

after_success:
  - pipenv run coveralls
