files:
  - source: /src/locale/en_US/LC_MESSAGES/django.po
    translation: /src/locale/%two_letters_code%/LC_MESSAGES/django.po
  - source: /src-ui/messages.xlf
    translation: /src-ui/src/locale/messages.%two_letters_code%.xlf
