files:
  - source: /src/documents/locale/en-us/LC_MESSAGES/django.po
    translation: /src/documents/locale/%two_letters_code%/LC_MESSAGES/django.po
  - source: /src-ui/messages.xlf
    translation: /src-ui/src/locale/messages.%two_letters_code%.xlf
