---
- name: update previous release to newest release
  hosts: all
  tasks:
    - name: set current version as installation target
      set_fact:
        paperlessng_version: 0.9.14

    - name: update to newest paperless-ng release
      include_role:
        name: ansible
