name: Bug report
description: Something is not working
title: "[BUG] Concise description of the issue"
labels: ["bug", "unconfirmed"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/paperless-ngx/paperless-ngx/discussions/new) or [ask in chat](https://matrix.to/#/#paperless:adnidor.de).
        
        Before opening an issue, please check [the documentation](https://paperless-ngx.readthedocs.io/en/latest/troubleshooting.html) and see if it helps you resolve your issue. Please also make sure that you followed the installation instructions.
        
        If you encounter issues while installing or configuring Paperless-ngx, please post in the ["Support" section of the discussions](https://github.com/paperless-ngx/paperless-ngx/discussions/new?category=support). Remember that Paperless successfully runs on a variety of different systems. If Paperless-ngx does not start, it's likely an issue with your system, not an issue of Paperless-ngx.
        
        Finally, please search issues and discussions before opening a new bug report.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Currently...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: "1. Go to '...', 2. Click on '....', 3. See error"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Webserver logs
      description: If available, post any logs from the web server related to your issue.
      render: bash
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: input
    id: version
    attributes:
      label: Paperless-ngx version
      placeholder: e.g. 1.6.0
    validations:
      required: true
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: Host OS of the machine running paperless-ngx
      placeholder: e.g. Archlinux / Ubuntu 20.04
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Docker
        - Bare metal
        - Other (please describe above)
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: Which browser you are using, if relevant
      placeholder: e.g. Chrome, Safari
  - type: input
    id: config-changes
    attributes:
      label: Configuration changes
      description: Any configuration changes you made in `docker-compose.yml`, `docker-compose.env` or `paperless.conf`.
  - type: input
    id: other
    attributes:
      label: Other
      description: Any other relevant details
