---
- name: update previous release to newest release
  hosts: all
  tasks:
    - name: set github ref as version when available
      set_fact:
        paperlessng_version: "{{ lookup('env', 'GITHUB_REF') | default('latest', True) }}"
    - name: update to newest paperless-ng release
      include_role:
        name: ansible
