---
name: Ansible Role

on: push

jobs:
  test:
  # https://molecule.readthedocs.io/en/latest/ci.html#github-actions
    runs-on: ubuntu-latest
    # https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
    if: contains(github.ref, 'refs/heads/')
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Set up Docker 
        uses: docker-practice/actions-setup-docker@master
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install molecule[ansible,docker]
          ansible --version
          docker --version
          molecule --version
          python --version
      - name: Test with molecule
        run: |
          cd ansible
          molecule test
        working-directory: "${{ github.repository }}"
